const express = require('express');
const router = express.Router();
const utentesRoutes = require('./utentes.routes');
const moradaRoutes = require('./morada.routes');
const loginRouter = require('./auth.routes');
const sessoesRoutes=require('./sessoes.routes.js');
const fisioRoutes=require('./fisioterapeutas.routes.js');
const notificacoesRoutes=require('./notificacoes.routes.js');
const feedbacksRoutes = require('./feedbacks.routes.js');
const planosRoutes = require('./planos.routes.js');
router.use('/planos', planosRoutes);
router.use('/notificacoes', notificacoesRoutes);
router.use('/feedbacks', feedbacksRoutes);
router.use('/fisioterapeutas', fisioRoutes);
router.use('/auth', loginRouter);
router.use('/sessoes', sessoesRoutes);
router.use('/utentes', utentesRoutes);
router.use('/api/morada', moradaRoutes); 
module.exports = router;